replicaCount: 1

livekit:
  # port: 7880
  log_level: info
  rtc:
    use_external_ip: true
    # default ports used
  #   udp_port: 7900
  #   tcp_port: 7901
  redis:
    address: <redis_host:port>
    # db: 0
    # username:
    # password:
  # one or more API key/secret pairs
  keys:
    myapikey: "myapisecret"
  # uncomment to enable tls TURN server
  # turn:
  #   enabled: true
  #   mountPath: "/etc/lkcert"
  #   secretName: <tlssecret>


loadBalancer:
  # create
  # valid values: disable, alb, aws, gke
  # in order to use alb, aws-ingress-controller must be installed
  # https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
  type: disable
  # Uncomment and enter host names if TLS is desired.
  # TLS is not supported with alb load balancers
  tls:
    # hosts:
    #   - livekit.myhost.com
    # with ALB, certificates needs to reside in ACM for self-discovery
    # with GKE, specify one or more secrets to use for the certificate
    # see: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-multi-ssl#specifying_certificates_for_your_ingress
    # secretName: <mysecret>

# when true (default), optimizes network stack for service
# increases UDP send and receive buffers
# optimizeNetwork: true

# autoscaling requires resources to be defined
autoscaling:
  # set to true to enable autoscaling. when set, ignores replicaCount
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# if LiveKit should run only on specific nodes
# this can be used to isolate designated nodes
nodeSelector: {}
  # node.kubernetes.io/instance-type: c5.2xlarge

resources: {}
  # Due to port restrictions, you can run only one instance of LiveKit per physical
  # node. Because of that, we recommend giving it plenty of resources to work with
  # limits:
  #   cpu: 6000m
  #   memory: 2048Mi
  # requests:
  #   cpu: 4000m
  #   memory: 1024Mi
