{{- if or (eq .Values.loadBalancer.type "gke") (eq .Values.loadBalancer.type "gke-managed-cert") (eq .Values.loadBalancer.type "gke-vpc-native") (eq .Values.loadBalancer.type "gclb") -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "livekit-server.fullname" . }}
spec:
  {{ .Values.gcp.backendConfig | toPrettyJson }}
{{ end }}