{{- if ne .Values.loadBalancer.type "disable" -}}
{{- $fullName := include "livekit-server.fullname" . -}}
{{- $svcPort := .Values.loadBalancer.servicePort -}}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- if eq .Values.loadBalancer.type "alb" }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- if .Values.loadBalancer.tls }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    {{- end }}
  {{- end }}
  {{- if eq .Values.loadBalancer.type "gke-managed-cert" }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.loadBalancer.staticIpName }}
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
  {{- end }}
  {{- if eq .Values.loadBalancer.type "do" }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.loadBalancer.clusterIssuer }}
  {{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
spec:
  defaultBackend:
    service:
      name:  {{ $fullName }}
      port:
        number: {{ $svcPort }}
{{- else -}}
apiVersion: extensions/v1beta1
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ $svcPort }}
{{- end }}
{{- with .Values.loadBalancer }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    {{- if .hosts }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName | quote }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
{{- end }}