apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit-server.fullname" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- if eq .Values.loadBalancer.type "aws" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- else if or (eq .Values.loadBalancer.type "gke") (eq .Values.loadBalancer.type "gke-managed-cert") }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"{{ .Values.loadBalancer.servicePort }}":"{{ include "livekit-server.fullname" . }}"}}'
  {{- end }}
spec:
  {{- if or (eq .Values.loadBalancer.type "alb") (eq .Values.loadBalancer.type "gke") (eq .Values.loadBalancer.type "gke-managed-cert") (eq .Values.loadBalancer.type "do") }}
  type: NodePort
  {{- else if eq .Values.loadBalancer.type "aws" }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.loadBalancer.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.livekit.prometheus_port }}
    - port: {{ .Values.livekit.prometheus_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "livekit-server.selectorLabels" . | nindent 4 }}
